"use client";
//import type { Metadata } from "next";
import "./globals.css";

import { ReactNode } from "react";
import Navbar from "@/components/Navbar";
import { useGuestId } from "@/hooks/useGuestId";
//import '@/styles/globals.css';

export default function RootLayout({ children }: { children: ReactNode }) {
  const guestId = useGuestId();
  return (
    <html lang="en">
      <head>
        <title>Tetris Battle</title>
        <meta name="description" content="Multiplayer Tetris game built with Next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="min-h-screen flex flex-col">
        <Navbar />
        <main className="flex-1 p-4 bg-gray-100 w-[75%] max-w-screen-2xl mx-auto px-4 ">{children}</main>
      </body>
    </html>
  );
}
// export const metadata: Metadata = {
//   title: "Tetris Battle",
//   description: "Generated by create next app",
// };
