import type { Metadata } from "next";
import "./globals.css";

import { ReactNode } from 'react';
import Navbar from '@/components/Navbar';
//import '@/styles/globals.css';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Navbar />
        <main className="flex-1 p-4 bg-gray-100 w-[75%] max-w-screen-2xl mx-auto px-4 ">
          {children}
        </main>
      </body>
    </html>
  );
}
export const metadata: Metadata = {
  title: "Tetris Battle",
  description: "Generated by create next app",
};


