FROM node:18-alpine as builder

WORKDIR /app

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

COPY package*.json ./

RUN npm install 
COPY . .

# stage 2
FROM node:18-alpine AS runner

WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/public ./public

# Mở cổng 3000 cho Next.js
EXPOSE 3000

# Chạy ứng dụng
CMD ["npm", "start"]